---
- name: confuring tomcat9
  hosts: all
  tasks: 
   - name: install tomcat9
     apt:
      name: tomcat9 
      state: present
      update_cache: yes
   - name: copy tomcta-user file 
     copy: 
      src: tomcat-users.xml
      dest: /etc/tomcat9     
   - name: change tha port ot tomcate 8080 ot 9090
     replace:
      regexp: 8080
      replace: 9090 
      path: /etc/tomcat9/server.xml 
   - name: restsrt tomcate9
     service: 
      name: tomcat9
      state: restarted 
   - name: check tha url in server ip 
     uri: 
      url: http://172.31.20.18
      status_code: 200      
